### ISSUE TITLE
impossible to use

### ISSUE THREAD

**Issue by antoinecastex** [googleapis/python-billingbudgets#109]
hello because there is no documentation , how to use it ?

from google.cloud import billing
client = billing.Client()

(like usual on all other GCP Python library) 

but :

Traceback (most recent call last):
  File "/Users/antoine.castex@loreal.com/localdev/main.py", line 432, in <module>
    list_budget()
  File "/Users/antoine.castex@loreal.com/localdev/main.py", line 429, in list_budget
    client = billing.Client()
AttributeError: module 'google.cloud.billing' has no attribute 'Client'

So , please can you explain how to use the library

**Comment by busunkim96** [comment]
Hi @antoinecastex,

Please see the generated reference docs https://googleapis.dev/python/billingbudgets/latest/index.html. If you've used other `google-cloud-*` libraries the surface of the client is very similar.

Is there a specific task you're looking to accomplish?

**Comment by parthea** [comment]
Hi @antoinecastex,

I've confirmed the docs are available in the readme on the homepage of https://github.com/googleapis/python-billingbudgets. I've filed a bug in a related repo for `Cloud Billing` to add a link in the readme to the documentation. See https://github.com/googleapis/python-billing/issues/90. I'm going to close this issue but please feel free to re-open it if you have additional questions.

**Comment by antoinecastex** [comment]
where did you see example of how to use here ?

https://googleapis.dev/python/billingbudgets/latest/index.html

there is nothing

i'm looking for something like that

https://pypi.org/project/google-cloud-resource-manager/

Start by authenticating:

$ gcloud auth application-default login
And then simply create a client:

from google.cloud import resource_manager
client = resource_manager.Client()
Using the API
Here’s a quick example of the full life-cycle:

from google.cloud import resource_manager

client = resource_manager.Client()

# List all projects you have access to
for project in client.list_projects():
    print(project)

# Create a new project
new_project = client.new_project(
 'your-project-id-here', name='My new project')
new_project.create()

# Update an existing project
project = client.fetch_project('my-existing-project')
project.name = 'Modified name'
project.update()

# Delete a project
project = client.new_project('my-existing-project')
project.delete()

# Undelete a project
project = client.new_project('my-existing-project')
project.undelete()


example of how to use your api

**Comment by busunkim96** [comment]
Hi @antoinecastex,

Yes, you are correct, there are no samples for this library. Unfortunately we don't currently have the bandwidth to write code snippets for every library, and snippet generation is further down the line.

If you could me know what specific task you're looking to accomplish I can write a short code snippet to help you get started.

**Comment by antoinecastex** [comment]
very basic stuff

i can help

today i test for example

from google.cloud.billing import budgets_v1

budgetsClient = budgets_v1.services.budget_service.BudgetServiceClient()
budgetsList = budgetClient.list_budgets(parent="billingAccounts/xxx")
for budget in budgetsList:
        print(budgets.name)

**Comment by nelsonmarcos** [comment]
Any update on this issue?

**Comment by parthea** [comment]
Autogenerated code snippets are available in the `generated_samples` folder.
https://github.com/googleapis/python-billingbudgets/tree/main/samples/generated_samples

For example, for `list_budgets` we have the following snippet.

The code snippets do not include the value for the `parent` arg. I'll transfer this issue to the repository that generates the code snippets so we can track improvements to the snippets that we generate.

```
def sample_list_budgets():
    # Create a client
    client = budgets_v1.BudgetServiceClient()

    # Initialize request argument(s)
    request = budgets_v1.ListBudgetsRequest(
        parent="parent_value",
    )

    # Make the request
    page_result = client.list_budgets(request=request)

    # Handle the response
    for response in page_result:
        print(response)
```
